source "https://rubygems.org"

ruby "~> 3.2"

gem "rails", "~> 7.1.0"
gem "puma", "~> 6.0"
gem "authio", "~> 0.1"
gem "sprockets-rails", require: "sprockets/railtie"
gem "bootsnap", require: false
gem "dotenv-rails", groups: [:development, :test]

group :development do
  gem "web-console"
end

group :test do
  gem "rspec-rails", "~> 6.0"
end
